# Generated by Django 4.2.7 on 2025-10-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('engineer', 'Инженер'), ('executive', 'Руководитель'), ('customer', 'Заказчик'), ('executor', 'Исполнитель'), ('viewer', 'Наблюдатель')], default='viewer', help_text='Роль пользователя в системе', max_length=20, verbose_name='Роль'),
        ),
    ]
