# Generated by Django 4.2.7 on 2025-10-06 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('MANAGER', 'Менеджер'), ('ENGINEER', 'Инженер'), ('EXECUTIVE', 'Руководитель'), ('CUSTOMER', 'Заказчик')], default='CUSTOMER', help_text='Роль пользователя в системе', max_length=20, verbose_name='Роль'),
        ),
    ]
