# Generated by Django 4.2.7 on 2024-01-15 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('title_template', models.CharField(max_length=200, verbose_name='Шаблон заголовка')),
                ('message_template', models.TextField(verbose_name='Шаблон сообщения')),
                ('email_subject_template', models.CharField(blank=True, max_length=200, verbose_name='Шаблон темы email')),
                ('email_body_template', models.TextField(blank=True, verbose_name='Шаблон тела email')),
                ('notification_type', models.CharField(choices=[('info', 'Информационное'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех'), ('reminder', 'Напоминание'), ('system', 'Системное')], default='info', max_length=20, verbose_name='Тип уведомления')),
                ('category', models.CharField(choices=[('general', 'Общие'), ('project', 'Проекты'), ('facility', 'Объекты'), ('document', 'Документы'), ('user', 'Пользователи'), ('system', 'Система'), ('security', 'Безопасность')], default='general', max_length=20, verbose_name='Категория')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет по умолчанию')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('default_expires_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Срок действия (дни)')),
                ('required_context_vars', models.JSONField(blank=True, default=list, verbose_name='Обязательные переменные контекста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_templates', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Шаблон уведомления',
                'verbose_name_plural': 'Шаблоны уведомлений',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('push_notifications', models.BooleanField(default=True, verbose_name='Push уведомления')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Начало тихих часов')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Конец тихих часов')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=50, verbose_name='Часовой пояс')),
                ('categories_enabled', models.JSONField(default=dict, verbose_name='Включенные категории')),
                ('digest_frequency', models.CharField(choices=[('never', 'Никогда'), ('daily', 'Ежедневно'), ('weekly', 'Еженедельно')], default='daily', max_length=20, verbose_name='Частота дайджеста')),
                ('auto_delete_read_after_days', models.PositiveIntegerField(default=30, verbose_name='Автоудаление прочитанных (дни)')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('last_logout_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний выход')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки уведомлений',
                'verbose_name_plural': 'Настройки уведомлений',
            },
        ),
        migrations.CreateModel(
            name='NotificationBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context_data', models.JSONField(blank=True, default=dict, verbose_name='Данные контекста')),
                ('total_recipients', models.PositiveIntegerField(default=0, verbose_name='Всего получателей')),
                ('successful_sends', models.PositiveIntegerField(default=0, verbose_name='Успешных отправок')),
                ('failed_sends', models.PositiveIntegerField(default=0, verbose_name='Неудачных отправок')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлен')),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Запланирован на')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлен в')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('recipients', models.ManyToManyField(related_name='notification_batches', to=settings.AUTH_USER_MODEL, verbose_name='Получатели')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='notifications.notificationtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Пакет уведомлений',
                'verbose_name_plural': 'Пакеты уведомлений',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('notification_type', models.CharField(choices=[('info', 'Информационное'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('success', 'Успех'), ('reminder', 'Напоминание'), ('system', 'Системное')], default='info', max_length=20, verbose_name='Тип')),
                ('category', models.CharField(choices=[('general', 'Общие'), ('project', 'Проекты'), ('facility', 'Объекты'), ('document', 'Документы'), ('user', 'Пользователи'), ('system', 'Система'), ('security', 'Безопасность')], default='general', max_length=20, verbose_name='Категория')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Прочитано в')),
                ('action_url', models.URLField(blank=True, verbose_name='Ссылка для действия')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_8b5c8a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f8a9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', 'priority'], name='notificatio_categor_d4e1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['expires_at'], name='notificatio_expires_a7b2c5_idx'),
        ),
    ]