# Generated by Django 4.2.7 on 2025-09-19 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_recipie_f8a9c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_categor_d4e1f3_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_8b5c8a_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_expires_4f3289_idx',
            old_name='notificatio_expires_a7b2c5_idx',
        ),
        migrations.RemoveField(
            model_name='notificationbatch',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='categories_enabled',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='digest_frequency',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='last_login_at',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='last_logout_at',
        ),
        migrations.RemoveField(
            model_name='notificationsettings',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='email_body_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='email_subject_template',
        ),
        migrations.RemoveField(
            model_name='notificationtemplate',
            name='required_context_vars',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Тип объекта'),
        ),
        migrations.AddField(
            model_name='notification',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID объекта'),
        ),
        migrations.AddField(
            model_name='notificationbatch',
            name='name',
            field=models.CharField(default='Пакет уведомлений', max_length=200, verbose_name='Название пакета'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='document_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о документах'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='facility_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления об объектах'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='high_priority_notifications',
            field=models.BooleanField(default=True, verbose_name='Высокий приоритет'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='low_priority_notifications',
            field=models.BooleanField(default=True, verbose_name='Низкий приоритет'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='normal_priority_notifications',
            field=models.BooleanField(default=True, verbose_name='Обычный приоритет'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='project_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления о проектах'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='security_notifications',
            field=models.BooleanField(default=True, verbose_name='Уведомления безопасности'),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='urgent_priority_notifications',
            field=models.BooleanField(default=True, verbose_name='Срочные уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL действия'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('project', 'Проект'), ('facility', 'Объект'), ('document', 'Документ'), ('user', 'Пользователь'), ('system', 'Система'), ('security', 'Безопасность')], default='system', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('system', 'Системное')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прочтения'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='context_data',
            field=models.JSONField(default=dict, verbose_name='Данные контекста'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_notification_batches', to=settings.AUTH_USER_MODEL, verbose_name='Создал'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='is_sent',
            field=models.BooleanField(default=False, verbose_name='Отправлено'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='recipients',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='notificationbatch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.notificationtemplate', verbose_name='Шаблон'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='auto_delete_read_after_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Удалять прочитанные через (дней)'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='category',
            field=models.CharField(choices=[('project', 'Проект'), ('facility', 'Объект'), ('document', 'Документ'), ('user', 'Пользователь'), ('system', 'Система'), ('security', 'Безопасность')], max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.CharField(help_text='Уникальный код для программного доступа', max_length=50, unique=True, verbose_name='Код шаблона'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='default_expires_days',
            field=models.PositiveIntegerField(blank=True, help_text='Количество дней, после которых уведомление истекает', null=True, verbose_name='Срок действия (дни)'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='message_template',
            field=models.TextField(help_text='Используйте {переменная} для подстановки значений', verbose_name='Шаблон сообщения'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='notification_type',
            field=models.CharField(choices=[('info', 'Информация'), ('success', 'Успех'), ('warning', 'Предупреждение'), ('error', 'Ошибка'), ('system', 'Системное')], default='info', max_length=20, verbose_name='Тип уведомления'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('normal', 'Обычный'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='normal', max_length=20, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='title_template',
            field=models.CharField(help_text='Используйте {переменная} для подстановки значений', max_length=200, verbose_name='Шаблон заголовка'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['category', '-created_at'], name='notificatio_categor_6dc2ff_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['priority', '-created_at'], name='notificatio_priorit_3fc670_idx'),
        ),
    ]
