# Generated by Django 4.2.7 on 2025-09-19 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_remove_notification_notificatio_recipie_f8a9c2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='description',
            field=models.TextField(blank=True, help_text='Описание назначения шаблона', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='email_body_template',
            field=models.TextField(blank=True, help_text='Используйте {{ переменная }} для подстановки значений', verbose_name='Шаблон тела email'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='email_subject_template',
            field=models.CharField(blank=True, help_text='Используйте {{ переменная }} для подстановки значений', max_length=200, verbose_name='Шаблон темы email'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='required_context_vars',
            field=models.JSONField(blank=True, default=list, help_text='Список переменных, которые должны быть переданы в контексте', verbose_name='Обязательные переменные контекста'),
        ),
    ]
