# Generated by Django 4.2.7 on 2025-10-05 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('testing', 'На проверке'), ('resolved', 'Решен'), ('closed', 'Закрыт'), ('rejected', 'Отклонен')], default='new', max_length=20, verbose_name='Статус')),
                ('severity', models.CharField(choices=[('low', 'Низкая'), ('medium', 'Средняя'), ('high', 'Высокая'), ('critical', 'Критическая')], default='medium', max_length=20, verbose_name='Серьезность')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Решен')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Местоположение')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оценочная стоимость')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая стоимость')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defects', to=settings.AUTH_USER_MODEL, verbose_name='Назначен')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='projects.facility', verbose_name='Объект')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_defects', to=settings.AUTH_USER_MODEL, verbose_name='Сообщил')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facility', 'status'], name='defects_def_facilit_b13862_idx'), models.Index(fields=['assigned_to', 'status'], name='defects_def_assigne_b0cc95_idx'), models.Index(fields=['severity', 'priority'], name='defects_def_severit_e380ec_idx'), models.Index(fields=['created_at'], name='defects_def_created_e170a5_idx')],
            },
        ),
    ]
