# Generated by Django 4.2.7 on 2025-10-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_initial'),
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='facilities.facility', verbose_name='Объект'),
        ),
    ]
