# Generated by Django 4.2.7 on 2025-10-05 00:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название объекта', max_length=200, verbose_name='Название объекта')),
                ('description', models.TextField(blank=True, help_text='Подробное описание объекта', verbose_name='Описание')),
                ('code', models.CharField(help_text='Уникальный код объекта в рамках проекта', max_length=50, verbose_name='Код объекта')),
                ('type', models.CharField(choices=[('building', 'Здание'), ('structure', 'Сооружение'), ('infrastructure', 'Инфраструктура'), ('equipment', 'Оборудование'), ('landscape', 'Благоустройство')], default='building', help_text='Тип объекта', max_length=20, verbose_name='Тип объекта')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('construction', 'Строительство'), ('testing', 'Тестирование'), ('completed', 'Завершен'), ('maintenance', 'Обслуживание'), ('decommissioned', 'Выведен из эксплуатации')], default='planning', help_text='Текущий статус объекта', max_length=20, verbose_name='Статус')),
                ('floor_count', models.PositiveIntegerField(blank=True, help_text='Количество этажей (для зданий)', null=True, verbose_name='Количество этажей')),
                ('area', models.DecimalField(blank=True, decimal_places=2, help_text='Общая площадь объекта в квадратных метрах', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Площадь (м²)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, help_text='Объем объекта в кубических метрах', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Объем (м³)')),
                ('location', models.CharField(blank=True, help_text='Конкретное местоположение объекта', max_length=200, verbose_name='Местоположение')),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=8, help_text='Географическая широта', max_digits=10, null=True, verbose_name='Широта')),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=8, help_text='Географическая долгота', max_digits=11, null=True, verbose_name='Долгота')),
                ('construction_start', models.DateField(blank=True, help_text='Дата начала строительства', null=True, verbose_name='Начало строительства')),
                ('construction_end', models.DateField(blank=True, help_text='Планируемая дата окончания строительства', null=True, verbose_name='Окончание строительства')),
                ('actual_completion', models.DateField(blank=True, help_text='Фактическая дата завершения строительства', null=True, verbose_name='Фактическое завершение')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Процент готовности объекта', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли объект', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_project_facilities', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'ordering': ['project', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Название проекта', max_length=200, verbose_name='Название проекта')),
                ('description', models.TextField(blank=True, help_text='Подробное описание проекта', verbose_name='Описание')),
                ('code', models.CharField(help_text='Уникальный код проекта', max_length=20, unique=True, verbose_name='Код проекта')),
                ('status', models.CharField(choices=[('planning', 'Планирование'), ('active', 'Активный'), ('on_hold', 'Приостановлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='planning', help_text='Текущий статус проекта', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='medium', help_text='Приоритет проекта', max_length=20, verbose_name='Приоритет')),
                ('client', models.CharField(blank=True, help_text='Название клиента или заказчика', max_length=200, verbose_name='Клиент')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, help_text='Бюджет проекта в рублях', max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Бюджет')),
                ('start_date', models.DateField(blank=True, help_text='Планируемая дата начала проекта', null=True, verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, help_text='Планируемая дата окончания проекта', null=True, verbose_name='Дата окончания')),
                ('actual_start_date', models.DateField(blank=True, help_text='Фактическая дата начала работ', null=True, verbose_name='Фактическая дата начала')),
                ('actual_end_date', models.DateField(blank=True, help_text='Фактическая дата завершения проекта', null=True, verbose_name='Фактическая дата окончания')),
                ('progress', models.PositiveIntegerField(default=0, help_text='Процент выполнения проекта', validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)')),
                ('location', models.CharField(blank=True, help_text='Адрес или местоположение проекта', max_length=200, verbose_name='Местоположение')),
                ('coordinates_lat', models.DecimalField(blank=True, decimal_places=8, help_text='Географическая широта', max_digits=10, null=True, verbose_name='Широта')),
                ('coordinates_lng', models.DecimalField(blank=True, decimal_places=8, help_text='Географическая долгота', max_digits=11, null=True, verbose_name='Долгота')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли проект', verbose_name='Активный')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Создан пользователем')),
                ('manager', models.ForeignKey(help_text='Ответственный менеджер проекта', on_delete=django.db.models.deletion.PROTECT, related_name='managed_projects', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('manager', 'Менеджер'), ('architect', 'Архитектор'), ('engineer', 'Инженер'), ('supervisor', 'Супервайзер'), ('worker', 'Рабочий'), ('inspector', 'Инспектор')], default='worker', help_text='Роль участника в проекте', max_length=20, verbose_name='Роль в проекте')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата присоединения')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата выхода')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный участник')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Участие в проекте',
                'verbose_name_plural': 'Участие в проектах',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectMembership', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
        migrations.CreateModel(
            name='FacilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название документа', max_length=200, verbose_name='Название документа')),
                ('description', models.TextField(blank=True, help_text='Описание документа', verbose_name='Описание')),
                ('type', models.CharField(choices=[('blueprint', 'Чертеж'), ('specification', 'Спецификация'), ('certificate', 'Сертификат'), ('report', 'Отчет'), ('photo', 'Фотография'), ('other', 'Другое')], default='other', help_text='Тип документа', max_length=20, verbose_name='Тип документа')),
                ('file', models.FileField(help_text='Файл документа', upload_to='facility_documents/', verbose_name='Файл')),
                ('version', models.CharField(default='1.0', help_text='Версия документа', max_length=20, verbose_name='Версия')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('is_active', models.BooleanField(default=True, help_text='Активен ли документ', verbose_name='Активный')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.facility', verbose_name='Объект')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_project_facility_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загружен пользователем')),
            ],
            options={
                'verbose_name': 'Документ объекта',
                'verbose_name_plural': 'Документы объектов',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='facility',
            name='project',
            field=models.ForeignKey(help_text='Проект, к которому относится объект', on_delete=django.db.models.deletion.CASCADE, related_name='project_facilities', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddField(
            model_name='facility',
            name='responsible_person',
            field=models.ForeignKey(blank=True, help_text='Ответственный за объект', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='responsible_facilities', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['project', 'is_active'], name='projects_pr_project_9b2313_idx'),
        ),
        migrations.AddIndex(
            model_name='projectmembership',
            index=models.Index(fields=['user', 'is_active'], name='projects_pr_user_id_f0db56_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmembership',
            unique_together={('project', 'user')},
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['priority'], name='projects_pr_priorit_a3d3b1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['manager'], name='projects_pr_manager_6dc9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['code'], name='projects_pr_code_80abae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['is_active'], name='projects_pr_is_acti_f7dee7_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['facility', 'type'], name='projects_fa_facilit_e6180f_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydocument',
            index=models.Index(fields=['is_active'], name='projects_fa_is_acti_312f39_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['project', 'status'], name='projects_fa_project_1aa1b3_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['type'], name='projects_fa_type_2f3953_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['responsible_person'], name='projects_fa_respons_2cc9f5_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_active'], name='projects_fa_is_acti_dadc48_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='facility',
            unique_together={('project', 'code')},
        ),
    ]
