# Generated by Django 4.2.7 on 2025-10-06 22:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Название задачи', max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, help_text='Подробное описание задачи', verbose_name='Описание')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('overdue', 'Просрочена'), ('cancelled', 'Отменена')], default='pending', help_text='Текущий статус задачи', max_length=20, verbose_name='Статус')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('urgent', 'Срочный')], default='medium', help_text='Приоритет задачи', max_length=20, verbose_name='Приоритет')),
                ('due_date', models.DateTimeField(blank=True, help_text='Крайний срок выполнения задачи', null=True, verbose_name='Срок выполнения')),
                ('completed_at', models.DateTimeField(blank=True, help_text='Дата фактического завершения задачи', null=True, verbose_name='Дата завершения')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, help_text='Оценочное время выполнения в часах', null=True, verbose_name='Оценочное время (часы)')),
                ('actual_hours', models.PositiveIntegerField(blank=True, help_text='Фактическое время выполнения в часах', null=True, verbose_name='Фактическое время (часы)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Назначена')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создана пользователем')),
                ('facility', models.ForeignKey(blank=True, help_text='Объект, к которому относится задача', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.facility', verbose_name='Объект')),
                ('project', models.ForeignKey(help_text='Проект, к которому относится задача', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='projects_ta_status_d6b74c_idx'), models.Index(fields=['priority'], name='projects_ta_priorit_dd6c2d_idx'), models.Index(fields=['assigned_to'], name='projects_ta_assigne_e8b2cd_idx'), models.Index(fields=['project'], name='projects_ta_project_71fd84_idx'), models.Index(fields=['facility'], name='projects_ta_facilit_82d5b8_idx'), models.Index(fields=['due_date'], name='projects_ta_due_dat_4757e0_idx')],
            },
        ),
    ]
