# Generated by Django 4.2.7 on 2025-09-19 04:29

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '__first__'),
        ('facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, help_text='CSS класс иконки', max_length=50, verbose_name='Иконка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Тип объекта',
                'verbose_name_plural': 'Типы объектов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Регион')),
                ('postal_code', models.CharField(blank=True, max_length=20, verbose_name='Почтовый индекс')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))], verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))], verbose_name='Долгота')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Общая площадь (м²)')),
                ('usable_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Полезная площадь (м²)')),
                ('floors_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество этажей')),
                ('construction_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Год постройки')),
                ('renovation_year', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)], verbose_name='Год последней реконструкции')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('inactive', 'Неактивный'), ('maintenance', 'На обслуживании'), ('renovation', 'На реконструкции'), ('demolished', 'Снесен')], default='active', max_length=20, verbose_name='Статус')),
                ('condition', models.CharField(choices=[('excellent', 'Отличное'), ('good', 'Хорошее'), ('satisfactory', 'Удовлетворительное'), ('poor', 'Плохое'), ('critical', 'Критическое')], default='good', max_length=20, verbose_name='Состояние')),
                ('condition_notes', models.TextField(blank=True, verbose_name='Примечания к состоянию')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Стоимость покупки')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Текущая стоимость')),
                ('insurance_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Страховая стоимость')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_facilities', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.facilitytype', verbose_name='Тип объекта')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_facilities', to=settings.AUTH_USER_MODEL, verbose_name='Управляющий')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='projects.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Объект недвижимости',
                'verbose_name_plural': 'Объекты недвижимости',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('frequency', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Еженедельно'), ('monthly', 'Ежемесячно'), ('quarterly', 'Ежеквартально'), ('semi_annually', 'Раз в полгода'), ('annually', 'Ежегодно'), ('custom', 'Пользовательский')], max_length=20, verbose_name='Периодичность')),
                ('custom_frequency_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Пользовательская периодичность (дни)')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('next_maintenance_date', models.DateField(verbose_name='Следующее обслуживание')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('paused', 'Приостановлен'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='active', max_length=20, verbose_name='Статус')),
                ('estimated_duration_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.1'))], verbose_name='Ожидаемая продолжительность (часы)')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ожидаемая стоимость')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='facilities.facility', verbose_name='Объект')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный')),
            ],
            options={
                'verbose_name': 'График обслуживания',
                'verbose_name_plural': 'Графики обслуживания',
                'ordering': ['next_maintenance_date'],
                'indexes': [models.Index(fields=['facility', 'status'], name='facilities__facilit_8e76b0_idx'), models.Index(fields=['next_maintenance_date'], name='facilities__next_ma_07a28f_idx'), models.Index(fields=['responsible_person'], name='facilities__respons_640c43_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='facilities/images/%Y/%m/', verbose_name='Изображение')),
                ('image_type', models.CharField(choices=[('exterior', 'Внешний вид'), ('interior', 'Интерьер'), ('floor_plan', 'План этажа'), ('technical', 'Техническое фото'), ('defect', 'Фото дефекта'), ('progress', 'Ход работ'), ('other', 'Другое')], default='other', max_length=20, verbose_name='Тип изображения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.facility', verbose_name='Объект')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_facility_images', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Изображение объекта',
                'verbose_name_plural': 'Изображения объектов',
                'ordering': ['order', '-uploaded_at'],
                'indexes': [models.Index(fields=['facility', 'image_type'], name='facilities__facilit_dfe72c_idx'), models.Index(fields=['is_primary'], name='facilities__is_prim_d6d491_idx')],
            },
        ),
        migrations.CreateModel(
            name='FacilityDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название документа')),
                ('document_type', models.CharField(choices=[('technical_passport', 'Технический паспорт'), ('ownership_certificate', 'Свидетельство о собственности'), ('construction_permit', 'Разрешение на строительство'), ('commissioning_act', 'Акт ввода в эксплуатацию'), ('floor_plan', 'Поэтажный план'), ('technical_plan', 'Технический план'), ('inspection_report', 'Отчет об обследовании'), ('insurance_policy', 'Страховой полис'), ('maintenance_contract', 'Договор обслуживания'), ('other', 'Другое')], max_length=30, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='facilities/documents/%Y/%m/', verbose_name='Файл')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('document_date', models.DateField(blank=True, null=True, verbose_name='Дата документа')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='facilities.facility', verbose_name='Объект')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_facility_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Документ объекта',
                'verbose_name_plural': 'Документы объектов',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['facility', 'document_type'], name='facilities__facilit_748227_idx'), models.Index(fields=['expiry_date'], name='facilities__expiry__892004_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['project', 'status'], name='facilities__project_ccbb47_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['facility_type', 'condition'], name='facilities__facilit_38a330_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['city', 'region'], name='facilities__city_b3eb87_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['created_at'], name='facilities__created_065e2f_idx'),
        ),
    ]
